<?php

namespace flowcode\pachamama\domain;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-31 at 12:01:55.
 */
class MailMessageTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var MailService
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new MailMessage();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers flowcode\pachamama\domain\MailMessage::getHtmlMail
     */
    public function testgetHtmlMail_simpleHtml_testOk() {
        $mailView = __DIR__ . "/_files/example.view.php";
        $params = array("name" => "somebody", "mail" => "somebody@mail.com");
        $to = "";
        $from = "";
        $subject = "";
        $mail = MailMessage::getHtmlMail($mailView, $params, $to, $from, $subject);
        $this->assertEquals($from, $mail->getFrom());
        $this->assertEquals("<a>somebody</a><a>somebody@mail.com</a>", $mail->getBody());
    }

    /**
     * @covers flowcode\pachamama\domain\MailMessage::getPlainMail
     */
    public function testgetPlainMail_simpleText_testOk() {
        $to = "";
        $from = "";
        $subject = "";
        $body = "hello";
        $mail = MailMessage::getPlainMail($to, $from, $body, $subject);
        $this->assertEquals($from, $mail->getFrom());
        $this->assertEquals("hello", $mail->getBody());
    }

}
